### ISSUE TITLE
Plugin no longer works

### ISSUE THREAD

**Issue by Endemoniada** [hmmh/atom-multifile-rename#3]
It seems the plugin has not worked for some time, on at least Atom 1.16.0 and 1.17.0.

Selecting multiple files and choosing "rename" will only rename the last file selected.

OS: macOS 10.12.4
Atom 1.17.0
multifile-rename: 0.1.5

**Comment by Endemoniada** [comment]
As I keep researching, it seems this is related to this bug: https://github.com/atom/tree-view/issues/1050

**Comment by kreativ-los** [comment]
Hey! Thanks for reporting this issue. I think atom refactored the tree view which caused this bug. 
With the latest patch this should work now. Please let me now if it does so that I can close this issue.

For some reason it's currently not possible to toggle multifile rename when you right click the file names directly. I'm working on a fix.

**Comment by Endemoniada** [comment]
No, sorry, still not working. "Toggle multifile rename" doesn't seem to do anything at all currently, no matter how I try to execute it. Selecting multiple files and right-click -> rename only renames one file.

**Comment by kreativ-los** [comment]
As I mentioned there is probably a bug with the tree views context menues.
You have to click beside the file name to get the right menu, then click on 'Rename Files' otherwise you get the context menu for a single file.
![Tree view bug](https://cloud.githubusercontent.com/assets/21077695/26343630/0f01bb82-3f9d-11e7-913e-12f3b7a72550.png)

**Comment by Endemoniada** [comment]
Yes, doing it like that, then it actually works. Thanks for the workaround!

**Comment by atomdmac** [comment]
FWIW, it looks like you can also work around this by holding `shift` while clicking.

**Comment by chriscurnow** [comment]
I just spent half an hour trying to work this out. Perhaps you could put some of this in the ReadMe.

Thanks for providing this package though. Even with the half hour spent trying to work out how to use it it has still saved me a lot of time 😄
